### ISSUE TITLE
Debug output is causing app to hang

### ISSUE THREAD

**Issue by doino-gretchenliev** [timefox/TeconMoon-s-WiiVC-Injector-Mod#7]
Although the new `BuildOutputBuffer` class looks more elegant, without buffering on the size of the output the app is becoming unstable with fast output. The high number of GC cycles issue is introduced again. Consider adding a buffer and flush it on size and not only on time. Also `BuildOutputBuffer` class is better suited for `Utils.cs` file(or `Log.cs`).

**Comment by timefox** [comment]
BuildOutputBuffer has been moved to Utils.cs now.
And in my machine, the hanging is mainly caused by too many invokes called. If I flushed buffer on size which means more frequently invokes with fast output, the things got even worse for me(I tested your code before, it makes faster output and reduced the memory usage, but it will hang a while at the last step). The purpose of using time driven buffer output only is reduing the count of invokes. I have given an initial buffer size for StringBuilder now which should improve the buffer performance. If it is still a problem, please let me know. I will see if I can figure out the key issues.

**Comment by doino-gretchenliev** [comment]
The initial size of the buffer should help as it will no prevent constantly allocating and deallocating memory. I will rebase my branch and give it a try.

**Comment by timefox** [comment]
OK, I hope it fixed the issue.

**Comment by doino-gretchenliev** [comment]
I test it with your last improvements. I can confirm the interface stays responsive during the hole building process now. Well done.

**Comment by timefox** [comment]
Well, it's good news.
